import 'package:flutter/material.dart';
import 'package:flutterapp/hackathonapp/generatedframewidget8/generated/GeneratedVectorWidget131.dart';
import 'package:flutterapp/hackathonapp/generatedframewidget8/generated/GeneratedVectorWidget126.dart';
import 'package:flutterapp/hackathonapp/generatedframewidget8/generated/GeneratedVectorWidget127.dart';
import 'package:flutterapp/hackathonapp/generatedframewidget8/generated/GeneratedVectorWidget130.dart';
import 'package:flutterapp/hackathonapp/generatedframewidget8/generated/GeneratedVectorWidget133.dart';
import 'package:flutterapp/hackathonapp/generatedframewidget8/generated/GeneratedVectorWidget132.dart';
import 'package:flutterapp/hackathonapp/generatedframewidget8/generated/GeneratedVectorWidget128.dart';
import 'package:flutterapp/hackathonapp/generatedframewidget8/generated/GeneratedVectorWidget125.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hackathonapp/generatedframewidget8/generated/GeneratedVectorWidget134.dart';
import 'package:flutterapp/hackathonapp/generatedframewidget8/generated/GeneratedGroupWidget23.dart';

/* Frame Frame
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrameWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 1.0;
                  double scaleX = (constraints.maxWidth * percentWidth) / 414.0;

                  double percentHeight = 1.0;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 896.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: 0,
                        translateY: 0,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget125())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.7705314009661836;
                  double scaleX = (constraints.maxWidth * percentWidth) / 319.0;

                  double percentHeight = 0.3247767857142857;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 291.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07971014492753623,
                        translateY: constraints.maxHeight * 0.29129464285714285,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget126())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.8043478260869565;
                  double scaleX = (constraints.maxWidth * percentWidth) / 333.0;

                  double percentHeight = 0.16294642857142858;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 146.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07971014492753623,
                        translateY: constraints.maxHeight * 0.6802455357142857,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget127())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.5664807010963919;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      234.52301025390625;

                  double percentHeight = 0.023035730634416853;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      20.6400146484375;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.10237680886678649,
                        translateY: constraints.maxHeight * 0.6408035414559501,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget128())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.22945894250547252;

                  final double height =
                      constraints.maxHeight * 0.023035730634416853;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.1388985546314774,
                        y: constraints.maxHeight * 0.7055356843130929,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget23(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.13768115942028986;
                  double scaleX = (constraints.maxWidth * percentWidth) / 57.0;

                  double percentHeight = 0.05357142857142857;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 48.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: 0,
                        translateY:
                            constraints.maxHeight * 0.025669642857142856,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget130())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.5091376926587976;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 210.7830047607422;

                  double percentHeight = 0.034151784011295865;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      30.599998474121094;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.08362318582580862,
                        translateY: constraints.maxHeight * 0.10629464047295707,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget131())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.12077294685990338;
                  double scaleX = (constraints.maxWidth * percentWidth) / 50.0;

                  double percentHeight = 0.04799107142857143;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 43.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07004830917874397,
                        translateY: constraints.maxHeight * 0.22544642857142858,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget132())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.426657045521022;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      176.63601684570312;

                  double percentHeight = 0.032022322927202494;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      28.692001342773438;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.2236135178718014,
                        translateY: constraints.maxHeight * 0.23575893470219203,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget133())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.7261304624990564;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 300.6180114746094;

                  double percentHeight = 0.11636607987540108;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      104.26400756835938;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.0915265659203276,
                        translateY: constraints.maxHeight * 0.3250446319580078,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget134())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
