import 'package:flutter/material.dart';
import 'package:flutterapp/hackathonapp/generateditem_rowviewwidget/generated/GeneratedPriceWidget.dart';
import 'package:flutterapp/hackathonapp/generateditem_rowviewwidget/generated/GeneratedButtonSecondaryWidget.dart';
import 'package:flutterapp/hackathonapp/generateditem_rowviewwidget/generated/GeneratedPurplecauliflowerWidget.dart';
import 'package:flutterapp/hackathonapp/generateditem_rowviewwidget/generated/GeneratedFrame27Widget.dart';
import 'package:flutterapp/hackathonapp/generateditem_rowviewwidget/generated/GeneratedMediaWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hackathonapp/generateditem_rowviewwidget/generated/GeneratedContainerWidget.dart';

/* Component Item_Row View
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedItem_RowViewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 160.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedContainerWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.427536231884058;

                final double height = constraints.maxHeight * 0.8;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04830917874396135,
                      y: constraints.maxHeight * 0.1,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedMediaWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.4323671497584541;

                final double height = constraints.maxHeight * 0.1625;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.5241545893719807,
                      y: constraints.maxHeight * 0.1,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedPurplecauliflowerWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 218.0,
              top: 52.0,
              right: null,
              bottom: null,
              width: 90.0,
              height: 22.0,
              child: GeneratedPriceWidget(),
            ),
            Positioned(
              left: 316.0,
              top: 104.0,
              right: null,
              bottom: null,
              width: 78.0,
              height: 40.0,
              child: GeneratedButtonSecondaryWidget(),
            ),
            Positioned(
              left: 218.0,
              top: 104.0,
              right: null,
              bottom: null,
              width: 78.0,
              height: 40.0,
              child: GeneratedFrame27Widget(),
            )
          ]),
    ));
  }
}
