import 'package:flutter/material.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedCAKESANDSWEETSWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedPersonWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedORNAMENTSANDDECORATIONSWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedTransportWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedRectangle56Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedSearchWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedPhoneWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedRectangle53Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedRectangle55Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedORGANICFRUITSANDVEGETABLESWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedRectangle54Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedPRODUCTSWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax2widget/generated/GeneratedSearchforproductsWidget.dart';

/* Frame iPhone 11 Pro Max - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 938.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 414.0,
                      height: 938.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 14.0,
                              right: null,
                              bottom: null,
                              width: 33.0,
                              height: 40.0,
                              child: GeneratedRectangle52Widget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 65.0,
                              height: 54.0,
                              child: TransformHelper.translate(
                                  x: -158.50,
                                  y: -373.00,
                                  z: 0,
                                  child: GeneratedTransportWidget()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 53.0,
                              height: 54.0,
                              child: TransformHelper.translate(
                                  x: -14.50,
                                  y: -371.00,
                                  z: 0,
                                  child: GeneratedPhoneWidget()),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 64.0,
                              height: 54.0,
                              child: TransformHelper.translate(
                                  x: 148.00,
                                  y: -373.00,
                                  z: 0,
                                  child: GeneratedPersonWidget()),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 110.0,
                              right: null,
                              bottom: null,
                              width: 169.0,
                              height: 52.0,
                              child: GeneratedPRODUCTSWidget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 157.0,
                              right: null,
                              bottom: null,
                              width: 343.0,
                              height: 48.0,
                              child: GeneratedRectangle53Widget(),
                            ),
                            Positioned(
                              left: 124.0,
                              top: 170.0,
                              right: null,
                              bottom: null,
                              width: 138.0,
                              height: 25.0,
                              child: GeneratedSearchforproductsWidget(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: TransformHelper.translate(
                                  x: -153.00,
                                  y: -267.00,
                                  z: 0,
                                  child: GeneratedSearchWidget()),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 219.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 177.0,
                              child: GeneratedRectangle54Widget(),
                            ),
                            Positioned(
                              left: 42.0,
                              top: 410.0,
                              right: null,
                              bottom: null,
                              width: 310.0,
                              height: 22.0,
                              child:
                                  GeneratedORGANICFRUITSANDVEGETABLESWidget(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 443.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 166.0,
                              child: GeneratedRectangle55Widget(),
                            ),
                            Positioned(
                              left: 96.0,
                              top: 623.0,
                              right: null,
                              bottom: null,
                              width: 188.0,
                              height: 22.0,
                              child: GeneratedCAKESANDSWEETSWidget(),
                            ),
                            Positioned(
                              left: 26.0,
                              top: 651.0,
                              right: null,
                              bottom: null,
                              width: 350.0,
                              height: 175.0,
                              child: GeneratedRectangle56Widget(),
                            ),
                            Positioned(
                              left: 52.0,
                              top: 840.0,
                              right: null,
                              bottom: null,
                              width: 290.0,
                              height: 22.0,
                              child: GeneratedORNAMENTSANDDECORATIONSWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
