import 'package:flutter/material.dart';
import 'package:flutterapp/hackathonapp/generatediconbikewidget/generated/GeneratedVectorWidget192.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hackathonapp/generatediconbikewidget/generated/GeneratedVectorWidget193.dart';
import 'package:flutterapp/hackathonapp/generatediconbikewidget/generated/GeneratedVectorWidget190.dart';
import 'package:flutterapp/hackathonapp/generatediconbikewidget/generated/GeneratedVectorWidget191.dart';

/* Component icon/bike
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconbikeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 24.0,
        height: 24.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.09444445371627808;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 2.266666889190674;

                  double percentHeight = 0.09444445371627808;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      2.266666889190674;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.5472217798233032,
                        translateY: constraints.maxHeight * 0.16666666666666666,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget190())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.3305555780728658;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 7.933333873748779;

                  double percentHeight = 0.42500007152557373;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      10.20000171661377;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.3583330313364665,
                        translateY: constraints.maxHeight * 0.35555557409922284,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget191())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.28333336114883423;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      6.8000006675720215;

                  double percentHeight = 0.28333336114883423;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      6.8000006675720215;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.07499995330969493,
                        translateY: constraints.maxHeight * 0.5916666189829508,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget192())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.28333336114883423;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      6.8000006675720215;

                  double percentHeight = 0.28333336114883423;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      6.8000006675720215;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.6416661341985067,
                        translateY: constraints.maxHeight * 0.5916666189829508,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget193())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
