import 'package:flutter/material.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax6widget/generated/GeneratedBUYNOWWidget1.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax6widget/generated/GeneratedRectangle71Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax6widget/generated/Generated5RSPIECEWidget1.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax6widget/generated/GeneratedRectangle72Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax6widget/generated/GeneratedPOTATOWidget1.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax6widget/generated/GeneratedFrameWidget11.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax6widget/generated/GeneratedORGANICPOTATOESFROMTHENATIVEVILLAGEOFTAMILNADUANDKERALA.dart';

/* Frame iPhone 11 Pro Max - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 11.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedFrameWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 407.0,
                height: 436.0,
                child: GeneratedRectangle71Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 162.0,
                height: 65.0,
                child: GeneratedPOTATOWidget1(),
              ),
              Positioned(
                left: 13.0,
                top: 612.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 56.0,
                child: Generated5RSPIECEWidget1(),
              ),
              Positioned(
                left: 13.0,
                top: 666.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 174.0,
                child:
                    GeneratedORGANICPOTATOESFROMTHENATIVEVILLAGEOFTAMILNADUANDKERALA(),
              ),
              Positioned(
                left: 77.0,
                top: 798.0,
                right: null,
                bottom: null,
                width: 260.0,
                height: 79.0,
                child: GeneratedRectangle72Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 820.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 38.0,
                child: GeneratedBUYNOWWidget1(),
              )
            ]),
      ),
    ));
  }
}
