import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hackathonapp/generatedicondronewidget/generated/GeneratedVectorWidget196.dart';

/* Component icon/Drone
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIconDroneWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 24.0,
        height: 24.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.9999983310699463;
                  double scaleX =
                      (constraints.maxWidth * percentWidth) / 23.99995994567871;

                  double percentHeight = 0.9998946189880371;
                  double scaleY = (constraints.maxHeight * percentHeight) /
                      23.99747085571289;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 7.103662937879562e-7,
                        translateY:
                            constraints.maxHeight * 0.00005240226164460182,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget196())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
