import 'package:flutter/material.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax1widget/generated/GeneratedLinkWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax1widget/generated/GeneratedBUYNOWWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax1widget/generated/GeneratedLocalyWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax1widget/generated/GeneratedSELLNOWWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax1widget/generated/GeneratedLocalyWidget1.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax1widget/generated/GeneratedRectangle47Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax1widget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax1widget/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax1widget/generated/GeneratedEllipse21Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax1widget/generated/GeneratedRectangle46Widget.dart';

/* Frame iPhone 11 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -231.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 1139.0,
                child: GeneratedRectangle46Widget(),
              ),
              Positioned(
                left: 147.0,
                top: 471.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 47.0,
                child: GeneratedLocalyWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 623.0,
                child: GeneratedRectangle47Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 53.0,
                child: GeneratedRectangle48Widget(),
              ),
              Positioned(
                left: 143.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 100.0,
                height: 43.0,
                child: GeneratedBUYNOWWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 712.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 51.0,
                child: GeneratedRectangle49Widget(),
              ),
              Positioned(
                left: 157.0,
                top: 718.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 43.0,
                child: GeneratedSELLNOWWidget(),
              ),
              Positioned(
                left: 137.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 97.0,
                child: GeneratedEllipse21Widget(),
              ),
              Positioned(
                left: 157.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 80.0,
                child: GeneratedLinkWidget(),
              ),
              Positioned(
                left: 148.0,
                top: 429.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 68.0,
                child: GeneratedLocalyWidget1(),
              )
            ]),
      ),
    ));
  }
}
