import 'package:flutter/material.dart';
import 'package:flutterapp/hackathonapp/generatedcell_rowviewwidget/generated/GeneratedRectangle45Widget.dart';
import 'package:flutterapp/hackathonapp/generatedcell_rowviewwidget/generated/GeneratedIconwalkingWidget1.dart';
import 'package:flutterapp/hackathonapp/generatedcell_rowviewwidget/generated/GeneratedIconcheckWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hackathonapp/generatedcell_rowviewwidget/generated/GeneratedTextWidget1.dart';

/* Component Cell_Row view
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCell_RowviewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 56.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle45Widget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.7898550724637681;

                final double height =
                    constraints.maxHeight * 0.4642857142857143;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.16666666666666666,
                      y: constraints.maxHeight * 0.2857142857142857,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedTextWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width =
                    constraints.maxWidth * 0.057971014492753624;

                final double height =
                    constraints.maxHeight * 0.42857142857142855;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.04830917874396135,
                      y: constraints.maxHeight * 0.2857142857142857,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIconwalkingWidget1(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width =
                    constraints.maxWidth * 0.057971014492753624;

                final double height =
                    constraints.maxHeight * 0.42857142857142855;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.893719806763285,
                      y: constraints.maxHeight * 0.2857142857142857,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIconcheckWidget2(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
