import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hackathonapp/generatedchipsselecetdwidget/generated/GeneratedIconcheckWidget.dart';
import 'package:flutterapp/hackathonapp/generatedchipsselecetdwidget/generated/GeneratedLabelWidget.dart';

/* Component Chips/Selecetd
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChipsSelecetdWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 98.0,
      height: 34.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(17.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(17.0),
              child: Container(
                color: Color.fromARGB(255, 213, 181, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.24489795918367346;

                final double height =
                    constraints.maxHeight * 0.7058823529411765;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.15306122448979592,
                      y: constraints.maxHeight * 0.14705882352941177,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedIconcheckWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.41836734693877553;

                final double height =
                    constraints.maxHeight * 0.7941176470588235;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.47959183673469385,
                      y: constraints.maxHeight * 0.17647058823529413,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedLabelWidget(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
