import 'package:flutter/material.dart';
import 'package:flutterapp/hackathonapp/generatedtextfieldwidget/generated/GeneratedHintWidget.dart';
import 'package:flutterapp/hackathonapp/generatedtextfieldwidget/generated/GeneratedContainerWidget1.dart';
import 'package:flutterapp/hackathonapp/generatedtextfieldwidget/generated/GeneratedTextWidget2.dart';

/* Component Text Field
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTextFieldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 374.0,
      height: 70.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: null,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: 48.0,
              child: GeneratedContainerWidget1(),
            ),
            Positioned(
              left: 13.0,
              top: 35.0,
              right: null,
              bottom: null,
              width: 33.0,
              height: 22.0,
              child: GeneratedTextWidget2(),
            ),
            Positioned(
              left: 14.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 35.0,
              height: 22.0,
              child: GeneratedHintWidget(),
            )
          ]),
    ));
  }
}
