import 'package:flutter/material.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedEllipse16Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedThumbupWidget2.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedFrameWidget10.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/Generated12RSPIECEWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedRectangle68Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedSendWidget1.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedSendWidget2.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/Generated5RSPIECEWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedThumbupWidget1.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedRectangle67Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedEllipse18Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedORANGESWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedRectangle65Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedEllipse19Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedRectangle66Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedORGANICVEGETABLESANDFRUITSWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedPOTATOWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedEllipse17Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedSendWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedSEARCHWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedEllipse20Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/Generated10RSPIECEWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedFrameWidget9.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax5widget/generated/GeneratedSTRAWBERRYWidget.dart';

/* Frame iPhone 11 Pro Max - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 12.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 40.0,
                child: GeneratedFrameWidget9(),
              ),
              Positioned(
                left: 12.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 56.0,
                child: GeneratedORGANICVEGETABLESANDFRUITSWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 41.0,
                child: GeneratedRectangle65Widget(),
              ),
              Positioned(
                left: 126.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 28.0,
                child: GeneratedSEARCHWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: -142.00,
                    y: -272.00,
                    z: 0,
                    child: GeneratedSearchWidget1()),
              ),
              Positioned(
                left: 12.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 141.0,
                child: GeneratedRectangle66Widget(),
              ),
              Positioned(
                left: 218.0,
                top: 227.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 24.0,
                child: GeneratedSTRAWBERRYWidget(),
              ),
              Positioned(
                left: 218.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 22.0,
                child: Generated10RSPIECEWidget(),
              ),
              Positioned(
                left: 221.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 43.0,
                child: GeneratedFrameWidget10(),
              ),
              Positioned(
                left: 305.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 53.0,
                height: 47.0,
                child: GeneratedEllipse16Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 131.00, y: -105.00, z: 0, child: GeneratedSendWidget()),
              ),
              Positioned(
                left: 12.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 142.0,
                child: GeneratedRectangle67Widget(),
              ),
              Positioned(
                left: 218.0,
                top: 408.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 29.0,
                child: GeneratedORANGESWidget(),
              ),
              Positioned(
                left: 221.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 22.0,
                child: Generated12RSPIECEWidget(),
              ),
              Positioned(
                left: 210.0,
                top: 505.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 45.0,
                child: GeneratedEllipse17Widget(),
              ),
              Positioned(
                left: 311.0,
                top: 508.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 45.0,
                child: GeneratedEllipse18Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 35.0,
                height: 29.0,
                child: TransformHelper.translate(
                    x: 33.50, y: 79.50, z: 0, child: GeneratedThumbupWidget1()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 131.00, y: 78.00, z: 0, child: GeneratedSendWidget1()),
              ),
              Positioned(
                left: 12.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 145.0,
                child: GeneratedRectangle68Widget(),
              ),
              Positioned(
                left: 223.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 32.0,
                child: GeneratedPOTATOWidget(),
              ),
              Positioned(
                left: 228.0,
                top: 658.0,
                right: null,
                bottom: null,
                width: 98.0,
                height: 22.0,
                child: Generated5RSPIECEWidget(),
              ),
              Positioned(
                left: 213.0,
                top: 694.0,
                right: null,
                bottom: null,
                width: 59.0,
                height: 55.0,
                child: GeneratedEllipse19Widget(),
              ),
              Positioned(
                left: 311.0,
                top: 693.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 56.0,
                child: GeneratedEllipse20Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: TransformHelper.translate(
                    x: 137.00, y: 270.00, z: 0, child: GeneratedSendWidget2()),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 39.0,
                height: 37.0,
                child: TransformHelper.translate(
                    x: 35.50,
                    y: 270.50,
                    z: 0,
                    child: GeneratedThumbupWidget2()),
              )
            ]),
      ),
    ));
  }
}
