import 'package:flutter/material.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedJOSEPHALEXKERALA767989Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedRectangle75Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedSUGGESIONSANDOPENIONSWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/Generated566766Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedADRESSSWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedRectangle78Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedRectangle79Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedRectangle77Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedRectangle76Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedFINISHPURCHASINGWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedVectorWidget141.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedPLEASEENTERYOURVALUABLESUGGESTIONSANDOPENIOSREGARDINGOU.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax7widget/generated/GeneratedFrameWidget13.dart';

/* Frame iPhone 11 Pro Max - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 407.0,
                height: 207.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedFrameWidget13(),
              ),
              Positioned(
                left: 73.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 24.0,
                child: GeneratedRectangle75Widget(),
              ),
              Positioned(
                left: 102.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 138.0,
                height: 28.0,
                child: Generated566766Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.043478260869565216;
                  double scaleX = (constraints.maxWidth * percentWidth) / 18.0;

                  double percentHeight = 0.022321428571428572;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 20.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.028985507246376812,
                        translateY: constraints.maxHeight * 0.33370535714285715,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget141())
                  ]);
                }),
              ),
              Positioned(
                left: 12.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 41.0,
                child: GeneratedADRESSSWidget(),
              ),
              Positioned(
                left: 73.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 98.0,
                child: GeneratedRectangle76Widget(),
              ),
              Positioned(
                left: 82.0,
                top: 309.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 80.0,
                child: GeneratedJOSEPHALEXKERALA767989Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 38.0,
                child: GeneratedSUGGESIONSANDOPENIONSWidget(),
              ),
              Positioned(
                left: 34.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 311.0,
                child: GeneratedRectangle77Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 224.0,
                child: GeneratedRectangle78Widget(),
              ),
              Positioned(
                left: 84.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 182.0,
                child:
                    GeneratedPLEASEENTERYOURVALUABLESUGGESTIONSANDOPENIOSREGARDINGOU(),
              ),
              Positioned(
                left: 25.0,
                top: 814.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 58.0,
                child: GeneratedRectangle79Widget(),
              ),
              Positioned(
                left: 73.0,
                top: 825.0,
                right: null,
                bottom: null,
                width: 239.0,
                height: 38.0,
                child: GeneratedFINISHPURCHASINGWidget(),
              )
            ]),
      ),
    ));
  }
}
