import 'package:flutter/material.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax8widget/generated/GeneratedRectangle81Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax8widget/generated/GeneratedTHANKYOUFORSHOPPINGWITHUSWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax8widget/generated/GeneratedCALL6456277267Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax8widget/generated/GeneratedMAILINFORMATIONDESHGMAILCOMWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax8widget/generated/GeneratedRectangle83Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax8widget/generated/GeneratedRectangle82Widget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax8widget/generated/GeneratedBacktohomepageWidget.dart';
import 'package:flutterapp/hackathonapp/generatediphone11promax8widget/generated/GeneratedANYENQUIRIESORSUGGESIONSWidget.dart';

/* Frame iPhone 11 Pro Max - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProMax8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 514.0,
                child: GeneratedRectangle81Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 119.0,
                child: GeneratedTHANKYOUFORSHOPPINGWITHUSWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 631.0,
                right: null,
                bottom: null,
                width: 367.0,
                height: 191.0,
                child: GeneratedRectangle82Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 631.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 74.0,
                child: GeneratedANYENQUIRIESORSUGGESIONSWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 725.0,
                right: null,
                bottom: null,
                width: 137.0,
                height: 92.0,
                child: GeneratedCALL6456277267Widget(),
              ),
              Positioned(
                left: 207.0,
                top: 707.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 113.0,
                child: GeneratedMAILINFORMATIONDESHGMAILCOMWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 826.0,
                right: null,
                bottom: null,
                width: 357.0,
                height: 51.0,
                child: GeneratedRectangle83Widget(),
              ),
              Positioned(
                left: 105.0,
                top: 833.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 38.0,
                child: GeneratedBacktohomepageWidget(),
              )
            ]),
      ),
    ));
  }
}
